### ISSUE TITLE
Sound stimuli with calibration?

### ISSUE THREAD

**Issue by vmousley** [yh-luo/psychopy_tobii_infant#1]
Hi, 

I have a question about your code from demo1_calibration. Is it designed to make a sound output when each keypress (0 - 9)? If not, is it possible to add sound?

Thanks!
Victoria

**Comment by yh-luo** [comment]
Hi Victoria,

It is currently unachievable to play a sound during calibration.
I imagined that you want to use sounds to attract the infant's attention?
I think it's a good implementation and I'll try to make it possible :smiley:

Best,
Yu-Han

**Comment by yh-luo** [comment]
@vmousley I have modified the package and created **demo6_calibration_with_sound.py** to test the new calibration procedure.
Can you download the current version and the demo sound file ([wawa.wav](https://bit.ly/2BnAGwG)) to see if that suits your need?
Thanks!

**Comment by yh-luo** [comment]
Because the current version of calibration _should_ be able to play a sound during collecting samples, this issue is closed.
