### ISSUE TITLE
'Result message' becomes invisible if using a white background

### ISSUE THREAD

**Issue by datalowe** [yh-luo/psychopy_tobii_infant#9]
The `run_calibration` and `run_validation` methods currently always use a white TextStim instance for displaying calibration/validation results. It's [recommended](https://www.tobiipro.com/learn-and-support/learn/steps-in-an-eye-tracking-study/run/performing-a-calibration-and-validation-in-pro-lab/) however that "[for] good performance, choose a calibration background that matches the color and brightness of your stimuli.". IIUC, this means that if a white background is used in the experiment itself, it's appropriate to use a white background for the calibration as well. But this hides the result message in this package.

One way to get around this is to simply add another argument to run_calibration/run_validation, like I did [here](https://github.com/datalowe/psychopy_tobii_infant/blob/specific_project/auto/psychopy_tobii_infant/__init__.py#L728).

**Comment by yh-luo** [comment]
It's a good one, thanks for reporting it! Since you already fixed it, could you open a PR for this enhancement and update documentation in `Args:` for `result_msg_color`? In that way you can get credit for it accordingly :slightly_smiling_face: 

On a side note, a white background is very bright and might cause discomfort to the subjects. Subjects may blink more, which is not desired in the calibration procedure. The calibration procedure provided by Tobii softwares use a dark background as well. If the stimuli are not very bright and fullscreen, I wouldn't recommend using a white background in the calibration procedure.

**Comment by datalowe** [comment]
> In that way you can get credit for it accordingly 🙂

Sure, I'm happy to do it, sorry I took so long. I just noticed I forgot to update the documentation as you'd suggested, I'll re-open the PR once I've done that.

> On a side note, a white background is very bright and might cause discomfort to the subjects. Subjects may blink more, which is not desired in the calibration procedure. The calibration procedure provided by Tobii softwares use a dark background as well. If the stimuli are not very bright and fullscreen, I wouldn't recommend using a white background in the calibration procedure.

Thanks for the tip, I understand your point. In the particular project I'm working on it's already been decided to use a white background during the experiment itself. This is partly due to practical reasons - it's much easier to find photos of everyday objects with perfectly white backgrounds, rather than with black ones. This might cause some discomfort as you note, but it's unavoidable in our case. 

Since our experiment itself uses a white background, the calibration should too, from what I gather. If one would instead use a black background anyway, this might lead to measurements being off since the pupil dilation during calibration and the experiment would differ. This is briefly described by a Tobii user [here](https://developer.tobii.com/community/forums/topic/calibration-background-color/).

**Comment by yh-luo** [comment]
@datalowe Thank you!
I will test the PR this week just to be sure. It looks good to me!

For your case, I would recommend that the experimenter instruct the participants not to blink during the collection of calibration samples ("when the circle stops shrinking" when using the default calibration procedure), but they are free to blink beside that.
In one of my early projects, we used a white background during calibration. Blinks were harmful for the calibration results and might prolong the calibration procedure. Hope my experience helps you!

**Comment by yh-luo** [comment]
It works like a charm, thank you again!
Closed in #12
